DROP TABLE if exists stats_visitor_info;
CREATE TABLE stats_visitor_info (
  visitor_id String primary key,
  visit_date String,
  visit_time Timestamp,
  ip_address String,
  country String,
  country_name String,
  region String,
  region_name String,
  city String,
  latitude String,
  longitude String,
  platform String,
  browser String,
  version String,
  mobile Integer,
  screen String,
  last_visit Timestamp 
);

DROP TABLE if exists stats_visitor_actions;
CREATE TABLE stats_visitor_actions (
click_id String Primary Key,
visitor_id String,
visit_date String,
visit_time Timestamp,
user_id Integer,
user_name String,
project_id Integer,
project_name String,
campaign_id Integer,
campaign_name String,
rule_id Integer,
rule_name String,
rule_type String,
rotator_id Integer,
rotator_name String,
rotator_type String,
service_id Integer,
service_name String,
source_id Integer,
source_name String,
domain_id Integer,
domain_name String,
offer_id Integer,
offer_name String,
linkhash String,
ip_address String,
traffic_type String,
country String,
country_name String,
region String,
region_name String,
city String,
latitude String,
longitude String,
platform String,
browser String,
version String,
mobile Integer,
screen String,
referer String,
sub1 String,
sub2 String,
sub3 String,
sub4 String,
sub5 String,
destination String,
page String,
query String,
duration Integer,
visits Integer,
clicks Integer,
click_time Timestamp,
revenue Float,
payout Float,
cost Float,
leads Integer,
lead_time Timestamp,
conversions Integer,
conversion_time Timestamp 
);
