use cobracmd;

TRUNCATE geo_countries;
INSERT INTO geo_countries (country,name) values ("A1","Anonymous Proxy");
INSERT INTO geo_countries (country,name) values ("A2","Satellite Provider");
INSERT INTO geo_countries (country,name) values ("O1","Other Country");
INSERT INTO geo_countries (country,name) values ("AD","Andorra");
INSERT INTO geo_countries (country,name) values ("AE","United Arab Emirates");
INSERT INTO geo_countries (country,name) values ("AF","Afghanistan");
INSERT INTO geo_countries (country,name) values ("AG","Antigua and Barbuda");
INSERT INTO geo_countries (country,name) values ("AI","Anguilla");
INSERT INTO geo_countries (country,name) values ("AL","Albania");
INSERT INTO geo_countries (country,name) values ("AM","Armenia");
INSERT INTO geo_countries (country,name) values ("AO","Angola");
INSERT INTO geo_countries (country,name) values ("AP","Asia/Pacific Region");
INSERT INTO geo_countries (country,name) values ("AQ","Antarctica");
INSERT INTO geo_countries (country,name) values ("AR","Argentina");
INSERT INTO geo_countries (country,name) values ("AS","American Samoa");
INSERT INTO geo_countries (country,name) values ("AT","Austria");
INSERT INTO geo_countries (country,name) values ("AU","Australia");
INSERT INTO geo_countries (country,name) values ("AW","Aruba");
INSERT INTO geo_countries (country,name) values ("AX","Aland Islands");
INSERT INTO geo_countries (country,name) values ("AZ","Azerbaijan");
INSERT INTO geo_countries (country,name) values ("BA","Bosnia and Herzegovina");
INSERT INTO geo_countries (country,name) values ("BB","Barbados");
INSERT INTO geo_countries (country,name) values ("BD","Bangladesh");
INSERT INTO geo_countries (country,name) values ("BE","Belgium");
INSERT INTO geo_countries (country,name) values ("BF","Burkina Faso");
INSERT INTO geo_countries (country,name) values ("BG","Bulgaria");
INSERT INTO geo_countries (country,name) values ("BH","Bahrain");
INSERT INTO geo_countries (country,name) values ("BI","Burundi");
INSERT INTO geo_countries (country,name) values ("BJ","Benin");
INSERT INTO geo_countries (country,name) values ("BL","Saint Bartelemey");
INSERT INTO geo_countries (country,name) values ("BM","Bermuda");
INSERT INTO geo_countries (country,name) values ("BN","Brunei Darussalam");
INSERT INTO geo_countries (country,name) values ("BO","Bolivia");
INSERT INTO geo_countries (country,name) values ("BQ","Bonaire, Saint Eustatius and Saba");
INSERT INTO geo_countries (country,name) values ("BR","Brazil");
INSERT INTO geo_countries (country,name) values ("BS","Bahamas");
INSERT INTO geo_countries (country,name) values ("BT","Bhutan");
INSERT INTO geo_countries (country,name) values ("BV","Bouvet Island");
INSERT INTO geo_countries (country,name) values ("BW","Botswana");
INSERT INTO geo_countries (country,name) values ("BY","Belarus");
INSERT INTO geo_countries (country,name) values ("BZ","Belize");
INSERT INTO geo_countries (country,name) values ("CA","Canada");
INSERT INTO geo_countries (country,name) values ("CC","Cocos (Keeling) Islands");
INSERT INTO geo_countries (country,name) values ("CD","Congo, The Democratic Republic of the");
INSERT INTO geo_countries (country,name) values ("CF","Central African Republic");
INSERT INTO geo_countries (country,name) values ("CG","Congo");
INSERT INTO geo_countries (country,name) values ("CH","Switzerland");
INSERT INTO geo_countries (country,name) values ("CI","Cote d'Ivoire");
INSERT INTO geo_countries (country,name) values ("CK","Cook Islands");
INSERT INTO geo_countries (country,name) values ("CL","Chile");
INSERT INTO geo_countries (country,name) values ("CM","Cameroon");
INSERT INTO geo_countries (country,name) values ("CN","China");
INSERT INTO geo_countries (country,name) values ("CO","Colombia");
INSERT INTO geo_countries (country,name) values ("CR","Costa Rica");
INSERT INTO geo_countries (country,name) values ("CU","Cuba");
INSERT INTO geo_countries (country,name) values ("CV","Cape Verde");
INSERT INTO geo_countries (country,name) values ("CW","Curacao");
INSERT INTO geo_countries (country,name) values ("CX","Christmas Island");
INSERT INTO geo_countries (country,name) values ("CY","Cyprus");
INSERT INTO geo_countries (country,name) values ("CZ","Czech Republic");
INSERT INTO geo_countries (country,name) values ("DE","Germany");
INSERT INTO geo_countries (country,name) values ("DJ","Djibouti");
INSERT INTO geo_countries (country,name) values ("DK","Denmark");
INSERT INTO geo_countries (country,name) values ("DM","Dominica");
INSERT INTO geo_countries (country,name) values ("DO","Dominican Republic");
INSERT INTO geo_countries (country,name) values ("DZ","Algeria");
INSERT INTO geo_countries (country,name) values ("EC","Ecuador");
INSERT INTO geo_countries (country,name) values ("EE","Estonia");
INSERT INTO geo_countries (country,name) values ("EG","Egypt");
INSERT INTO geo_countries (country,name) values ("EH","Western Sahara");
INSERT INTO geo_countries (country,name) values ("ER","Eritrea");
INSERT INTO geo_countries (country,name) values ("ES","Spain");
INSERT INTO geo_countries (country,name) values ("ET","Ethiopia");
INSERT INTO geo_countries (country,name) values ("EU","Europe");
INSERT INTO geo_countries (country,name) values ("FI","Finland");
INSERT INTO geo_countries (country,name) values ("FJ","Fiji");
INSERT INTO geo_countries (country,name) values ("FK","Falkland Islands (Malvinas)");
INSERT INTO geo_countries (country,name) values ("FM","Micronesia, Federated States of");
INSERT INTO geo_countries (country,name) values ("FO","Faroe Islands");
INSERT INTO geo_countries (country,name) values ("FR","France");
INSERT INTO geo_countries (country,name) values ("GA","Gabon");
INSERT INTO geo_countries (country,name) values ("GB","United Kingdom");
INSERT INTO geo_countries (country,name) values ("GD","Grenada");
INSERT INTO geo_countries (country,name) values ("GE","Georgia");
INSERT INTO geo_countries (country,name) values ("GF","French Guiana");
INSERT INTO geo_countries (country,name) values ("GG","Guernsey");
INSERT INTO geo_countries (country,name) values ("GH","Ghana");
INSERT INTO geo_countries (country,name) values ("GI","Gibraltar");
INSERT INTO geo_countries (country,name) values ("GL","Greenland");
INSERT INTO geo_countries (country,name) values ("GM","Gambia");
INSERT INTO geo_countries (country,name) values ("GN","Guinea");
INSERT INTO geo_countries (country,name) values ("GP","Guadeloupe");
INSERT INTO geo_countries (country,name) values ("GQ","Equatorial Guinea");
INSERT INTO geo_countries (country,name) values ("GR","Greece");
INSERT INTO geo_countries (country,name) values ("GS","South Georgia and the South Sandwich Islands");
INSERT INTO geo_countries (country,name) values ("GT","Guatemala");
INSERT INTO geo_countries (country,name) values ("GU","Guam");
INSERT INTO geo_countries (country,name) values ("GW","Guinea-Bissau");
INSERT INTO geo_countries (country,name) values ("GY","Guyana");
INSERT INTO geo_countries (country,name) values ("HK","Hong Kong");
INSERT INTO geo_countries (country,name) values ("HM","Heard Island and McDonald Islands");
INSERT INTO geo_countries (country,name) values ("HN","Honduras");
INSERT INTO geo_countries (country,name) values ("HR","Croatia");
INSERT INTO geo_countries (country,name) values ("HT","Haiti");
INSERT INTO geo_countries (country,name) values ("HU","Hungary");
INSERT INTO geo_countries (country,name) values ("ID","Indonesia");
INSERT INTO geo_countries (country,name) values ("IE","Ireland");
INSERT INTO geo_countries (country,name) values ("IL","Israel");
INSERT INTO geo_countries (country,name) values ("IM","Isle of Man");
INSERT INTO geo_countries (country,name) values ("IN","India");
INSERT INTO geo_countries (country,name) values ("IO","British Indian Ocean Territory");
INSERT INTO geo_countries (country,name) values ("IQ","Iraq");
INSERT INTO geo_countries (country,name) values ("IR","Iran, Islamic Republic of");
INSERT INTO geo_countries (country,name) values ("IS","Iceland");
INSERT INTO geo_countries (country,name) values ("IT","Italy");
INSERT INTO geo_countries (country,name) values ("JE","Jersey");
INSERT INTO geo_countries (country,name) values ("JM","Jamaica");
INSERT INTO geo_countries (country,name) values ("JO","Jordan");
INSERT INTO geo_countries (country,name) values ("JP","Japan");
INSERT INTO geo_countries (country,name) values ("KE","Kenya");
INSERT INTO geo_countries (country,name) values ("KG","Kyrgyzstan");
INSERT INTO geo_countries (country,name) values ("KH","Cambodia");
INSERT INTO geo_countries (country,name) values ("KI","Kiribati");
INSERT INTO geo_countries (country,name) values ("KM","Comoros");
INSERT INTO geo_countries (country,name) values ("KN","Saint Kitts and Nevis");
INSERT INTO geo_countries (country,name) values ("KP","Korea, Democratic People's Republic of");
INSERT INTO geo_countries (country,name) values ("KR","Korea, Republic of");
INSERT INTO geo_countries (country,name) values ("KW","Kuwait");
INSERT INTO geo_countries (country,name) values ("KY","Cayman Islands");
INSERT INTO geo_countries (country,name) values ("KZ","Kazakhstan");
INSERT INTO geo_countries (country,name) values ("LA","Lao People's Democratic Republic");
INSERT INTO geo_countries (country,name) values ("LB","Lebanon");
INSERT INTO geo_countries (country,name) values ("LC","Saint Lucia");
INSERT INTO geo_countries (country,name) values ("LI","Liechtenstein");
INSERT INTO geo_countries (country,name) values ("LK","Sri Lanka");
INSERT INTO geo_countries (country,name) values ("LR","Liberia");
INSERT INTO geo_countries (country,name) values ("LS","Lesotho");
INSERT INTO geo_countries (country,name) values ("LT","Lithuania");
INSERT INTO geo_countries (country,name) values ("LU","Luxembourg");
INSERT INTO geo_countries (country,name) values ("LV","Latvia");
INSERT INTO geo_countries (country,name) values ("LY","Libyan Arab Jamahiriya");
INSERT INTO geo_countries (country,name) values ("MA","Morocco");
INSERT INTO geo_countries (country,name) values ("MC","Monaco");
INSERT INTO geo_countries (country,name) values ("MD","Moldova, Republic of");
INSERT INTO geo_countries (country,name) values ("ME","Montenegro");
INSERT INTO geo_countries (country,name) values ("MF","Saint Martin");
INSERT INTO geo_countries (country,name) values ("MG","Madagascar");
INSERT INTO geo_countries (country,name) values ("MH","Marshall Islands");
INSERT INTO geo_countries (country,name) values ("MK","Macedonia");
INSERT INTO geo_countries (country,name) values ("ML","Mali");
INSERT INTO geo_countries (country,name) values ("MM","Myanmar");
INSERT INTO geo_countries (country,name) values ("MN","Mongolia");
INSERT INTO geo_countries (country,name) values ("MO","Macao");
INSERT INTO geo_countries (country,name) values ("MP","Northern Mariana Islands");
INSERT INTO geo_countries (country,name) values ("MQ","Martinique");
INSERT INTO geo_countries (country,name) values ("MR","Mauritania");
INSERT INTO geo_countries (country,name) values ("MS","Montserrat");
INSERT INTO geo_countries (country,name) values ("MT","Malta");
INSERT INTO geo_countries (country,name) values ("MU","Mauritius");
INSERT INTO geo_countries (country,name) values ("MV","Maldives");
INSERT INTO geo_countries (country,name) values ("MW","Malawi");
INSERT INTO geo_countries (country,name) values ("MX","Mexico");
INSERT INTO geo_countries (country,name) values ("MY","Malaysia");
INSERT INTO geo_countries (country,name) values ("MZ","Mozambique");
INSERT INTO geo_countries (country,name) values ("NA","Namibia");
INSERT INTO geo_countries (country,name) values ("NC","New Caledonia");
INSERT INTO geo_countries (country,name) values ("NE","Niger");
INSERT INTO geo_countries (country,name) values ("NF","Norfolk Island");
INSERT INTO geo_countries (country,name) values ("NG","Nigeria");
INSERT INTO geo_countries (country,name) values ("NI","Nicaragua");
INSERT INTO geo_countries (country,name) values ("NL","Netherlands");
INSERT INTO geo_countries (country,name) values ("NO","Norway");
INSERT INTO geo_countries (country,name) values ("NP","Nepal");
INSERT INTO geo_countries (country,name) values ("NR","Nauru");
INSERT INTO geo_countries (country,name) values ("NU","Niue");
INSERT INTO geo_countries (country,name) values ("NZ","New Zealand");
INSERT INTO geo_countries (country,name) values ("OM","Oman");
INSERT INTO geo_countries (country,name) values ("PA","Panama");
INSERT INTO geo_countries (country,name) values ("PE","Peru");
INSERT INTO geo_countries (country,name) values ("PF","French Polynesia");
INSERT INTO geo_countries (country,name) values ("PG","Papua New Guinea");
INSERT INTO geo_countries (country,name) values ("PH","Philippines");
INSERT INTO geo_countries (country,name) values ("PK","Pakistan");
INSERT INTO geo_countries (country,name) values ("PL","Poland");
INSERT INTO geo_countries (country,name) values ("PM","Saint Pierre and Miquelon");
INSERT INTO geo_countries (country,name) values ("PN","Pitcairn");
INSERT INTO geo_countries (country,name) values ("PR","Puerto Rico");
INSERT INTO geo_countries (country,name) values ("PS","Palestinian Territory");
INSERT INTO geo_countries (country,name) values ("PT","Portugal");
INSERT INTO geo_countries (country,name) values ("PW","Palau");
INSERT INTO geo_countries (country,name) values ("PY","Paraguay");
INSERT INTO geo_countries (country,name) values ("QA","Qatar");
INSERT INTO geo_countries (country,name) values ("RE","Reunion");
INSERT INTO geo_countries (country,name) values ("RO","Romania");
INSERT INTO geo_countries (country,name) values ("RS","Serbia");
INSERT INTO geo_countries (country,name) values ("RU","Russian Federation");
INSERT INTO geo_countries (country,name) values ("RW","Rwanda");
INSERT INTO geo_countries (country,name) values ("SA","Saudi Arabia");
INSERT INTO geo_countries (country,name) values ("SB","Solomon Islands");
INSERT INTO geo_countries (country,name) values ("SC","Seychelles");
INSERT INTO geo_countries (country,name) values ("SD","Sudan");
INSERT INTO geo_countries (country,name) values ("SE","Sweden");
INSERT INTO geo_countries (country,name) values ("SG","Singapore");
INSERT INTO geo_countries (country,name) values ("SH","Saint Helena");
INSERT INTO geo_countries (country,name) values ("SI","Slovenia");
INSERT INTO geo_countries (country,name) values ("SJ","Svalbard and Jan Mayen");
INSERT INTO geo_countries (country,name) values ("SK","Slovakia");
INSERT INTO geo_countries (country,name) values ("SL","Sierra Leone");
INSERT INTO geo_countries (country,name) values ("SM","San Marino");
INSERT INTO geo_countries (country,name) values ("SN","Senegal");
INSERT INTO geo_countries (country,name) values ("SO","Somalia");
INSERT INTO geo_countries (country,name) values ("SR","Suriname");
INSERT INTO geo_countries (country,name) values ("SS","South Sudan");
INSERT INTO geo_countries (country,name) values ("ST","Sao Tome and Principe");
INSERT INTO geo_countries (country,name) values ("SV","El Salvador");
INSERT INTO geo_countries (country,name) values ("SX","Sint Maarten");
INSERT INTO geo_countries (country,name) values ("SY","Syrian Arab Republic");
INSERT INTO geo_countries (country,name) values ("SZ","Swaziland");
INSERT INTO geo_countries (country,name) values ("TC","Turks and Caicos Islands");
INSERT INTO geo_countries (country,name) values ("TD","Chad");
INSERT INTO geo_countries (country,name) values ("TF","French Southern Territories");
INSERT INTO geo_countries (country,name) values ("TG","Togo");
INSERT INTO geo_countries (country,name) values ("TH","Thailand");
INSERT INTO geo_countries (country,name) values ("TJ","Tajikistan");
INSERT INTO geo_countries (country,name) values ("TK","Tokelau");
INSERT INTO geo_countries (country,name) values ("TL","Timor-Leste");
INSERT INTO geo_countries (country,name) values ("TM","Turkmenistan");
INSERT INTO geo_countries (country,name) values ("TN","Tunisia");
INSERT INTO geo_countries (country,name) values ("TO","Tonga");
INSERT INTO geo_countries (country,name) values ("TR","Turkey");
INSERT INTO geo_countries (country,name) values ("TT","Trinidad and Tobago");
INSERT INTO geo_countries (country,name) values ("TV","Tuvalu");
INSERT INTO geo_countries (country,name) values ("TW","Taiwan");
INSERT INTO geo_countries (country,name) values ("TZ","Tanzania, United Republic of");
INSERT INTO geo_countries (country,name) values ("UA","Ukraine");
INSERT INTO geo_countries (country,name) values ("UG","Uganda");
INSERT INTO geo_countries (country,name) values ("UM","United States Minor Outlying Islands");
INSERT INTO geo_countries (country,name) values ("US","United States");
INSERT INTO geo_countries (country,name) values ("UY","Uruguay");
INSERT INTO geo_countries (country,name) values ("UZ","Uzbekistan");
INSERT INTO geo_countries (country,name) values ("VA","Holy See (Vatican City State)");
INSERT INTO geo_countries (country,name) values ("VC","Saint Vincent and the Grenadines");
INSERT INTO geo_countries (country,name) values ("VE","Venezuela");
INSERT INTO geo_countries (country,name) values ("VG","Virgin Islands, British");
INSERT INTO geo_countries (country,name) values ("VI","Virgin Islands, U.S.");
INSERT INTO geo_countries (country,name) values ("VN","Vietnam");
INSERT INTO geo_countries (country,name) values ("VU","Vanuatu");
INSERT INTO geo_countries (country,name) values ("WF","Wallis and Futuna");
INSERT INTO geo_countries (country,name) values ("WS","Samoa");
INSERT INTO geo_countries (country,name) values ("YE","Yemen");
INSERT INTO geo_countries (country,name) values ("YT","Mayotte");
INSERT INTO geo_countries (country,name) values ("ZA","South Africa");
INSERT INTO geo_countries (country,name) values ("ZM","Zambia");
INSERT INTO geo_countries (country,name) values ("ZW","Zimbabwe");
INSERT INTO geo_countries (country,name) values ("XX",'Unknown');

UPDATE geo_countries SET sort = 10 WHERE country = 'US';
UPDATE geo_countries SET sort = 9 WHERE country = 'CA';
UPDATE geo_countries SET sort = 8 WHERE country = 'GB';
UPDATE geo_countries SET sort = 7 WHERE country = 'MX';


INSERT INTO records 
(domain_id, name, type, content, ttl, prio, change_date, rule_id, internal) 
VALUES 
(1,'e.cobralytics.com','A','54.86.76.180',300,0,'2014-05-13 11:59:46',0,1),
(1,'e.cobralytics.com','A','54.174.90.96',300,0,'2014-05-13 11:59:46',0,1),
(1,'ns1.cobralytics.com','A','54.174.90.96',300,0,'2014-05-13 11:59:46',0,1),
(1,'ns2.cobralytics.com','A','54.86.76.180',300,0,'2014-05-13 11:59:46',0,1),
(1,'app.cobralytics.com','A','54.86.76.180',300,0,'2014-05-13 11:59:46',0,1),
(1,'app.cobralytics.com','A','54.174.90.96',300,0,'2014-05-13 11:59:46',0,1);



